on: 
  schedule:
    - cron: "0 */12 * * *"

name: Push Tweet / Toot With Progress

jobs:
  tweetntoot:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install Scrapy + Mastodon.py
        run: |
          pip install scrapy Mastodon.py
      - name: Generate Toot
        run: |
          scrapy runspider spider.py
        env: 
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
